//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiWithDotNetFramework2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch
    {
        public string batchid { get; set; }
        public Nullable<System.DateTime> bsdate { get; set; }
        public Nullable<int> bstrength { get; set; }
        public string courseid { get; set; }
    }
}
