//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiWithDotNetFramework2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public string courseid { get; set; }
        public string coursename { get; set; }
        public string coursecategory { get; set; }
        public Nullable<decimal> coursefees { get; set; }
        public Nullable<int> courseduration { get; set; }
    }
}
