//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiWithDotNetFramework2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public string sid { get; set; }
        public string sname { get; set; }
        public Nullable<System.DateTime> sdob { get; set; }
        public string scity { get; set; }
        public string squal { get; set; }
        public string semail { get; set; }
        public string sphone { get; set; }
    }
}
